Effect-TS/language-service

.changeset/fuzzy-apes-move.md
docs/modules/quickinfo.ts.md
docs/modules/refactors.ts.md
docs/modules/transformer.ts.md
src/index.ts
src/quickinfo.ts

dedupe identical jsdoc tags

---

.changeset/lazy-ducks-hunt.md
examples/diagnostics/floatingEffect.ts
src/diagnostics/floatingEffect.ts
src/diagnostics/missingEffectContext.ts
src/diagnostics/missingEffectError.ts
src/diagnostics/missingStarInYieldEffectGen.ts
src/utils/TypeParser.ts

Now Fiber and FiberRuntime are not checked for floatingEffects diagnostics

allow Fiber and FiberRuntime to be floating

---

.changeset/icy-ghosts-jog.md
examples/diagnostics/missingStarInYieldEffectGen.ts
src/diagnostics/missingStarInYieldEffectGen.ts
src/utils/TypeParser.ts
test/__snapshots__/diagnostics.test.ts.snap

Handle Effect.fn and Effect.fnUntraced in missing yield star diagnostic. The generator will be checked in the same way we check Effect.gen

Handle Effect.fn and Effect.fnUntraced in missing yield star diagnostic

---

.changeset/lemon-bears-teach.md
examples/refactors/toggleTypeAnnotation.ts
src/refactors/toggleTypeAnnotation.ts
test/__snapshots__/refactors.test.ts.snap

Now refactor toggle return type is available inside property declarations of classes, such as
```ts
class Test {
static live /*<- here */ = "value to infer type from"
}
```

Add support for toggle type annotation in class property members

---

.changeset/new-lamps-hope.md
README.md
examples/refactors/removeUnnecessaryEffectGen.ts
src/diagnostics/unnecessaryEffectGen.ts
src/quickinfo.ts
src/refactors.ts
src/refactors/asyncAwaitToGen.ts
src/refactors/asyncAwaitToGenTryPromise.ts
src/refactors/effectGenToFn.ts
src/refactors/functionToArrow.ts
src/refactors/pipeableToDatafirst.ts
src/refactors/removeUnnecessaryEffectGen.ts
src/refactors/toggleLazyConst.ts
src/refactors/toggleReturnTypeAnnotation.ts
src/refactors/toggleTypeAnnotation.ts
src/utils/AST.ts
test/__snapshots__/refactors.test.ts.snap

This PR adds a new refactor which removes unnecessary `Effect.gen` calls by simplifying generator functions that only wrap a single `yield*` statement returning an `Effect`. This refactor replaces the `Effect.gen` wrapper with the inner `Effect` directly, making the code more concise and readable.
n/a

Add refactor: remove unnecessary Effect.gen

---

.changeset/evil-seas-pay.md
README.md
examples/refactors/wrapWithEffectGen.ts
src/core/AST.ts
src/refactors.ts
src/refactors/wrapWithEffectGen.ts
test/__snapshots__/refactors.test.ts.snap

Adds refactor which wraps an `Effect` expression with `Effect.gen`
- Related Issue #92 and #96
After the Nano refactor, my PR #92 never got merged, and the related PR #96 didn't include the commits from #92.
(See comment https://github.com/Effect-TS/language-service/pull/92#issuecomment-2823849226)
I'm open to all feedback and hope we can work together to get it through, as my team have said this refactor would be useful.

Add refactor wrapWithEffectGen

---

.changeset/chubby-meals-drum.md
examples/refactors/makeSchemaOpaque.ts
examples/refactors/makeSchemaOpaque_shortImport.ts
examples/refactors/makeSchemaOpaque_shortImportAlias.ts
examples/refactors/makeSchemaOpaque_union.ts
src/refactors.ts
src/refactors/asyncAwaitToGen.ts
src/refactors/asyncAwaitToGenTryPromise.ts
src/refactors/effectGenToFn.ts
src/refactors/functionToArrow.ts
src/refactors/makeSchemaOpaque.ts
src/refactors/pipeableToDatafirst.ts
src/refactors/removeUnnecessaryEffectGen.ts
src/refactors/toggleLazyConst.ts
src/refactors/toggleReturnTypeAnnotation.ts
src/refactors/toggleTypeAnnotation.ts
src/refactors/wrapWithEffectGen.ts
src/refactors/wrapWithPipe.ts
src/utils/TypeParser.ts
test/__snapshots__/refactors.test.ts.snap

This PR adds a refactor that given a variable that declares a schema, it will automatically generate opaque types for the schema type, encoded and context, and re-export the schema with the new opaque types.
Given:
```ts
import { Schema } from "effect"
export const MyStruct = Schema.Struct({
id: Schema.Number,
name: Schema.String
})
```
will output
```ts
import { Schema } from "effect"
export const MyStruct_ = Schema.Struct({
id: Schema.Number,
name: Schema.String
})
export interface MyStruct extends Schema.Schema.Type<typeof MyStruct_> { }
export interface MyStructEncoded extends Schema.Schema.Encoded<typeof MyStruct_> { }
export type MyStructContext = Schema.Schema.Context<typeof MyStruct_>
export const MyStruct: Schema.Schema<MyStruct, MyStructEncoded, MyStructContext> = MyStruct_
```

Schema opaque refactor

---

.changeset/olive-pans-taste.md
examples/refactors/makeSchemaOpaqueWithNs_shortImport.ts
src/refactors.ts
src/refactors/makeSchemaOpaque.ts
src/refactors/makeSchemaOpaqueWithNs.ts
test/__snapshots__/refactors.test.ts.snap

```ts
export const MyStruct_ = Schema.Struct({
id: Schema.Number,
name: Schema.String
})
export interface MyStruct extends Schema.Schema.Type<typeof MyStruct_> { }
export namespace MyStruct {
export interface Encoded extends Schema.Schema.Encoded<typeof MyStruct_> { }
export type Context = Schema.Schema.Context<typeof MyStruct_>
}
export const MyStruct: Schema.Schema<MyStruct, MyStruct.Encoded, MyStruct.Context> = MyStruct_
```

Add refactor to make schema opaque with namespaces

---

.changeset/wise-queens-search.md
README.md
package.json
pnpm-lock.yaml
src/core/LSP.ts
src/index.ts
src/transform.ts
tsup.config.ts

With this PR we add a SourceTransformer compatible with ts-patch that allows emitting diagnostics at compile time.
tspc should be used instead of tsc, and transform should be configured as well inside tsconfig.json

Support ts-patch transformer to emit diagnostics at compile time

---

.changeset/warm-sloths-tie.md
examples/refactors/typeToEffectSchema_literal.ts
src/utils/SchemaGen.ts
test/__snapshots__/refactors.test.ts.snap

`type MyType = "a" | "b"`
was producing
`export const MyType = Schema.Union(Schema.Literal("a"), Schema.Literal("b"))`
now outputs
`export const MyType = Schema.Literal("a", "b")`

Use a single Schema.Literal call in unions of literals

---

.changeset/open-beans-enter.md
examples/diagnostics/missingEffectContext_arrowReturnType.ts
examples/diagnostics/missingEffectContext_conciseBody.ts
src/core/TypeCheckerApi.ts
test/__snapshots__/diagnostics.test.ts.snap

Fix previously wrongly reported cases such as:
```ts
export const test2: {
<A, E, R>(eff: Effect.Effect<A, E, R>): Effect.Effect<A, E, Exclude<R, Scope.Scope>>
} = <A, E, R>(eff: Effect.Effect<A, E, R>) => Effect.void.pipe(Effect.andThen(eff), Effect.scoped)
```

Improve arrow function handling for type inference

---

.changeset/cute-suns-own.md
examples/refactors/effectGenToFn_mixedPipes.ts
examples/refactors/effectGenToFn_withPipes.ts
src/refactors/effectGenToFn.ts
test/__snapshots__/refactors.test.ts.snap

Fix issue with refactor removing pipe arguments in some edge cases

Fix handling of nested pipes in effectGenToFn refactor

---

.changeset/great-hotels-sell.md
examples/refactors/typeToEffectSchema_typeOf.ts
src/refactors/typeToEffectSchema.ts
src/refactors/typeToEffectSchemaClass.ts
src/utils/SchemaGen.ts
test/__snapshots__/refactors.test.ts.snap

When a top level typeof node is encuntered, it's type will be resolved and treated. Nested typeof node won't be considered to avoid circular references.
- Related Issue #157 
- Closes #157

In type to effect schema, follow top level typeof nodes

---

.changeset/blue-windows-divide.md
src/index.ts

In some configurations, LSP may be applied multiple times to the same env. Use a flag to detect and avoid multiple applications on the same instance proxy.

Avoid multiple LSP patching

---

.changeset/blue-times-speak.md
.vscode/settings.json
src/diagnostics/missingReturnYieldStar.ts
test/__snapshots__/diagnostics/missingReturnYieldStar.ts.output

use "succeeds" instead of "completes"

Improve message for return yield* diagnostic

---

README.md

Use `jsonc` for supporting comments in the configuration examples preventing red lines.
- Related Issue #
- Closes #

docs: use `jsonc` for better reading

---

.changeset/proud-kiwis-fail.md
src/completions/middlewareAutoImports.ts

When barrelImportPackages is enabled, top-level function re-exports like "pipe" are now redirected to top barrel instead of prefixed

Add exclusion rules for barrel style

---

.changeset/fine-houses-throw.md
examples/refactors/togglePipeStyle.ts
src/core/TypeParser.ts
src/refactors.ts
src/refactors/togglePipeStyle.ts
test/__snapshots__/refactors/togglePipeStyle.ts.ln5col54.output
test/__snapshots__/refactors/togglePipeStyle.ts.ln7col32.output

Provides a refactor that changes style of pipe from/to X.pipe(Y) and pipe(X, Y)
- Closes #204

Add refactor to toggle pipe style

---

.changeset/bitter-lights-tie.md
docgen.json
examples/refactors/makeSchemaOpaque_brand.ts
src/refactors/makeSchemaOpaque.ts
test/__snapshots__/refactors/makeSchemaOpaque_brand.ts.ln4col17.output

Properly detect when to use type aliases and when to use interface extends

Fix make schema opaque for non-object and non-union schemas

---

.changeset/cli-shebang-update.md
src/cli.ts

- Add `#!/usr/bin/env node` shebang to `src/cli.ts` for proper executable support
- Update CLI version from 0.0.1 to 0.0.2
The shebang allows the CLI to be executed directly as a script when installed globally or through npx:
```bash
#!/usr/bin/env node
```

Add shebang to CLI entry point

---

.changeset/old-hounds-kneel.md
src/cli/patch.ts
src/cli/utils.ts

This PR changes the way _tsc.js and typescript.js are patched in order to produce a more "standalone-like" output code.
This means that now fake "source sections" between `// src/XXXX.ts` are produced, so that ts-patch can still treat them as standalone typescript source files.
The utils have been moved from before the heading, to before the last "source section".
This allows vue-tsc to not get confused in which instance to patch to support arbitrary .vue file extensions.

Comply with ts-patch and vue-tsc patching mechanism
