Effect-TS/language-service

- .changeset/shaggy-pandas-dream.md
- examples/diagnostics/missingStarInYieldEffectGen.ts
- src/diagnostics/missingStarInYieldEffectGen.ts
- src/utils/TypeParser.ts
- test/__snapshots__/diagnostics.test.ts.snap
- test/diagnostics.test.ts
Adds an additional diagnostic over the function* keyword
> Additional notice for misused yield instead of yield*

- README.md
> clearer install instructions

- .changeset/shy-hands-find.md
- README.md
- examples/diagnostics/unnecessaryEffectGen.ts
- src/diagnostics.ts
- src/diagnostics/unnecessaryEffectGen.ts
- test/__snapshots__/diagnostics.test.ts.snap
> unnecessary effect gen

- .changeset/loose-breads-search.md
- README.md
- examples/refactors/effectGenToFn.ts
- src/refactors.ts
- src/refactors/effectGenToFn.ts
- src/utils/TypeParser.ts
- test/__snapshots__/refactors.test.ts.snap
Add refactor that converts functions returning Effect.gen into Effect.fn
- Closes #75
> Add refactor to rewrite Effect.gen to Effect.fn

- .changeset/dull-symbols-hang.md
- examples/refactors/asyncAwaitToGenTryPromise_anonymous.ts
- examples/refactors/asyncAwaitToGen_anonymous.ts
- src/refactors/asyncAwaitToGen.ts
- src/refactors/asyncAwaitToGenTryPromise.ts
- test/__snapshots__/refactors.test.ts.snap
Fix async await to gen in case of anonymous functions.
> Fix async await to effect gen with anonymous functions

- .changeset/stale-berries-look.md
- examples/refactors/effectGenToFn_classMethod.ts
- src/refactors/effectGenToFn.ts
- src/utils/AST.ts
- test/__snapshots__/refactors.test.ts.snap
Handle refactor gen to fn in class methods
> Handle refactor gen to fn in class methods

- .changeset/tiny-teams-greet.md
- src/refactors/asyncAwaitToGen.ts
- src/refactors/asyncAwaitToGenTryPromise.ts
- src/utils/AST.ts
Always use type information to resolve Effect module name
> Always use type information to resolve Effect module name

- .changeset/brown-clowns-shave.md
- src/diagnostics/unnecessaryEffectGen.ts
> Fix useless gen severity

- .changeset/cute-onions-double.md
- src/diagnostics/unnecessaryEffectGen.ts
- src/refactors/removeUnnecessaryEffectGen.ts
- src/utils/AST.ts
Fix accidental bundle of ts in lsp
> Fix accidental bundle of ts in lsp

- .changeset/cute-kings-think.md
- src/core/LSP.ts
- src/diagnostics/floatingEffect.ts
- src/diagnostics/missingEffectContext.ts
- src/diagnostics/missingEffectError.ts
- src/diagnostics/missingStarInYieldEffectGen.ts
- src/diagnostics/unnecessaryEffectGen.ts
- src/index.ts
- src/utils/AST.ts
- test/__snapshots__/diagnostics.test.ts.snap
- test/diagnostics.test.ts
- test/refactors.test.ts
- test/utils/mocks.ts
This PR introduces "fix" over diagnostics. Allowing things like missing yield* or unnecessary effect gen to provide an inline quickfix.
> Lsp diagnostics codefixes

- .changeset/fancy-ads-peel.md
- src/completions.ts
- src/core/LSP.ts
- src/core/Nano.ts
- src/diagnostics/floatingEffect.ts
- src/diagnostics/missingEffectContext.ts
- src/diagnostics/missingEffectError.ts
- src/diagnostics/missingStarInYieldEffectGen.ts
- src/diagnostics/unnecessaryEffectGen.ts
- src/index.ts
- src/utils/AST.ts
- src/utils/TypeCheckerApi.ts
- src/utils/TypeParser.ts
- test/Nano.test.ts
- test/diagnostics.test.ts
- test/refactors.test.ts
Optimize hot paths and introduce internal caching for expensive APIs
> Optimize hot paths and introduce internal caching for expensive APIs

- .changeset/some-ends-visit.md
- README.md
- examples/completions/contextSelfInClasses.ts
- examples/completions/effectSchemaSelfInClasses_dotToken.ts
- examples/completions/effectSchemaSelfInClasses_tagg.ts
- examples/completions/effectSelfInClasses.ts
- src/completions.ts
- src/completions/contextSelfInClasses.ts
- src/completions/effectSchemaSelfInClasses.ts
- src/completions/effectSelfInClasses.ts
- src/core/LSP.ts
- src/utils/AST.ts
- test/__snapshots__/completions.test.ts.snap
- test/completions.test.ts
- tsconfig.examples.json
When extending classes and using Effect.Service, Context.Tag, etc...
- Closes #82
> Add support for smart completions for effect classes with "Self"

- .changeset/wicked-dolls-read.md
- examples/demo.ts
- tsup.config.ts
> Ship readme

- .changeset/fruity-lands-worry.md
- examples/completions/effectDataClasses.ts
- src/completions.ts
- src/completions/effectDataClasses.ts
- test/__snapshots__/completions.test.ts.snap
- test/__snapshots__/refactors.test.ts.snap
Add support for completions for Data.TaggedClass and Data.TaggedError
> Add support for completions for Data.TaggedClass and Data.TaggedError

- .changeset/icy-cameras-dig.md
- src/core/LSP.ts
- src/index.ts
- test/diagnostics.test.ts
solve codefixes and diagnostics in a single pass and cache between them
> solve codefixes and diagnostics in a single pass and cache between them

- .changeset/warm-towns-feel.md
- examples/diagnostics/unnecessaryEffectGen_ifBlock.ts
- src/core/Nano.ts
- src/diagnostics/unnecessaryEffectGen.ts
- test/__snapshots__/diagnostics.test.ts.snap
- test/completions.test.ts
- test/diagnostics.test.ts
- test/refactors.test.ts
If blocks with a single line were mistakenly matched against unnecessary effect gen
> Fix single line if blocks mismatched as unnecessary gen

- package.json
- pnpm-lock.yaml
- test/perf.ts
Add perf command for dev testing
> add perf command

- README.md
Fixed typo from `npm` to `npx` and added note that `ts-patch` needs to be installed manually and isn't a dependency of `language-service` and won't be installed automatically when installing `language-service`.
> Update README.md: updated info on compile-time diagnostics

- .changeset/lucky-squids-bow.md
- examples/refactors/typeToEffectSchema.ts
- examples/refactors/typeToEffectSchemaClass.ts
- examples/refactors/typeToEffectSchema_conditionalType.ts
- examples/refactors/typeToEffectSchema_dataTypes.ts
- examples/refactors/typeToEffectSchema_indexSignature.ts
- examples/refactors/typeToEffectSchema_noGenerics.ts
- examples/refactors/typeToEffectSchema_typeAlias.ts
- src/core/Nano.ts
- src/refactors.ts
- src/refactors/typeToEffectSchema.ts
- src/refactors/typeToEffectSchemaClass.ts
- src/utils/SchemaGen.ts
- test/__snapshots__/refactors.test.ts.snap
This refactor allows, when positioned over an interface or type alias name, to refactor it to a schema or a schema.class
> Type to schema

- .changeset/slick-cars-cheer.md
- examples/refactors/typeToEffectSchema.ts
- src/utils/SchemaGen.ts
- test/__snapshots__/refactors.test.ts.snap
Add record and intersection support to type to effect schema
> Add missing record and intersection into type to schema refactor

- src/core/Nano.ts
- test/perf.ts
> proto perf

- README.md
Add instructions for nvim-vtsls
> Add nvim plugins help link

- src/core/LSP.ts
- src/core/Nano.ts
- src/diagnostics/unnecessaryEffectGen.ts
> Various internal cleanups

- .changeset/busy-years-invent.md
- examples/refactors/typeToEffectSchema.ts
- src/utils/SchemaGen.ts
- test/__snapshots__/refactors.test.ts.snap
Handle generation of keyof for type to schema refactor
> Handle generation of keyof for type to schema refactor

- .changeset/sad-areas-tickle.md
- examples/diagnostics/floatingEffect_poolSubtype.ts
- src/utils/TypeParser.ts
- test/__snapshots__/diagnostics/floatingEffect_poolSubtype.ts.codefixes
- test/__snapshots__/diagnostics/floatingEffect_poolSubtype.ts.output
Add Pool as effect subtype allowed to be floating
> Add Pool as effect subtype allowed to be floating

- .changeset/cruel-rabbits-dance.md
- examples/diagnostics/floatingEffect_logicalAssignments.ts
- src/diagnostics/floatingEffect.ts
- test/__snapshots__/diagnostics/floatingEffect_logicalAssignments.ts.codefixes
- test/__snapshots__/diagnostics/floatingEffect_logicalAssignments.ts.output
Fix false positive of logical assignments
- Related Issue #166
- Closes #166
> Fix false positive of logical assignments closes #166

- .changeset/easy-oranges-pull.md
- README.md
- examples/quickinfo/layerInfo.ts
- src/core/TypeCheckerApi.ts
- src/index.ts
- src/quickinfo.ts
- src/quickinfo/dedupeJsDocs.ts
- src/quickinfo/effectTypeArgs.ts
- src/quickinfo/layerInfo.ts
- src/utils/TypeParser.ts
> Add quickinfo for Layers

- .changeset/better-baths-repeat.md
- examples/diagnostics/missingReturnYieldStar.ts
- src/diagnostics.ts
- src/diagnostics/missingReturnYieldStar.ts
- test/__snapshots__/diagnostics/missingReturnYieldStar.ts.codefixes
- test/__snapshots__/diagnostics/missingReturnYieldStar.ts.missingReturnYieldStar_fix.from288to318.output
- test/__snapshots__/diagnostics/missingReturnYieldStar.ts.missingReturnYieldStar_fix.from429to452.output
- test/__snapshots__/diagnostics/missingReturnYieldStar.ts.missingReturnYieldStar_fix.from457to481.output
- test/__snapshots__/diagnostics/missingReturnYieldStar.ts.missingReturnYieldStar_skipFile.from288to318.output
- test/__snapshots__/diagnostics/missingReturnYieldStar.ts.missingReturnYieldStar_skipFile.from429to452.output
- test/__snapshots__/diagnostics/missingReturnYieldStar.ts.missingReturnYieldStar_skipFile.from457to481.output
- test/__snapshots__/diagnostics/missingReturnYieldStar.ts.missingReturnYieldStar_skipNextLine.from288to318.output
- test/__snapshots__/diagnostics/missingReturnYieldStar.ts.missingReturnYieldStar_skipNextLine.from429to452.output
- test/__snapshots__/diagnostics/missingReturnYieldStar.ts.missingReturnYieldStar_skipNextLine.from457to481.output
- test/__snapshots__/diagnostics/missingReturnYieldStar.ts.output
- Related Issue #94
- Closes #94
> Add error when yield* with never-completing effect is not returned

- .changeset/six-bears-train.md
- README.md
- examples/goto/rpc.ts
- examples/goto/rpc_defs.ts
- src/core/TypeScriptApi.ts
- src/diagnostics/duplicatePackage.ts
- src/goto.ts
- src/goto/effectRpcDefinition.ts
- src/index.ts
Resolves Rpc definition when goto-definition over Rpc client
> Allow goto definition to Jump to Rpc definition object

- .changeset/open-days-invent.md
- examples/completions/rpcMakeClasses.ts
- examples/goto/rpc.ts
- examples/goto/rpc_defs.ts
- src/completions.ts
- src/completions/rpcMakeClasses.ts
- test/__snapshots__/completions.test.ts.snap
Add completions for Rpc.make while declaring classes
> Add completions for Rpc.make while declaring classes

- .changeset/cold-humans-wash.md
- src/utils/SchemaGen.ts
> Fix parenthesized type handling in type to schema

- README.md
- src/core/TypeParser.ts
> optimize hot path

- .changeset/busy-boxes-stop.md
- README.md
- examples/diagnostics/unnecessaryPipe.ts
- src/core/AST.ts
- src/core/TypeParser.ts
- src/diagnostics.ts
- src/diagnostics/unnecessaryPipe.ts
- src/quickinfo/layerInfo.ts
- src/refactors/effectGenToFn.ts
- test/__snapshots__/diagnostics/unnecessaryPipe.ts.codefixes
- test/__snapshots__/diagnostics/unnecessaryPipe.ts.output
- test/__snapshots__/diagnostics/unnecessaryPipe.ts.unnecessaryPipe_fix.from313to315.output
- test/__snapshots__/diagnostics/unnecessaryPipe.ts.unnecessaryPipe_fix.from352to370.output
- test/__snapshots__/diagnostics/unnecessaryPipe.ts.unnecessaryPipe_skipFile.from313to315.output
- test/__snapshots__/diagnostics/unnecessaryPipe.ts.unnecessaryPipe_skipFile.from352to370.output
- test/__snapshots__/diagnostics/unnecessaryPipe.ts.unnecessaryPipe_skipNextLine.from313to315.output
- test/__snapshots__/diagnostics/unnecessaryPipe.ts.unnecessaryPipe_skipNextLine.from352to370.output
- Related Issue #203
- Closes #203
> Report unnecessary pipe

- src/index.ts
> Add start log

- .changeset/blue-bars-turn.md
- src/index.ts
> Add starting log

- .changeset/thin-yaks-taste.md
- README.md
The Svelte LSP does not properly compose with other LSPs when using SvelteKit. So the Effect LSP should be loaded as last entry to ensure proper composition.
If you did not installed the Svelte LSP into your local project but instead through the Svelte VSCode extension, we recommend instead to install locally and add it as first entry. That way it won't be applied by the VSCode extension.
Your tsconfig should look like this:
```json
{
"compilerOptions": {
"plugins": [
{ "name": "typescript-svelte-plugin" },
{ "name": "@effect/language-service" }
]
}
}
```
- Closes #165
> Add documentation for usage with SvelteKit LSP

- .changeset/cyan-horses-enter.md
- examples/diagnostics/returnEffectInGen_noDiagnostics.ts
- examples/diagnostics/returnEffectInGen_warn.ts
- src/diagnostics.ts
- src/diagnostics/returnEffectInGen.ts
- test/__snapshots__/diagnostics/returnEffectInGen_noDiagnostics.ts.codefixes
- test/__snapshots__/diagnostics/returnEffectInGen_noDiagnostics.ts.output
- test/__snapshots__/diagnostics/returnEffectInGen_warn.ts.codefixes
- test/__snapshots__/diagnostics/returnEffectInGen_warn.ts.output
- test/__snapshots__/diagnostics/returnEffectInGen_warn.ts.returnEffectInGen_fix.from86to113.output
- test/__snapshots__/diagnostics/returnEffectInGen_warn.ts.returnEffectInGen_skipFile.from86to113.output
- test/__snapshots__/diagnostics/returnEffectInGen_warn.ts.returnEffectInGen_skipNextLine.from86to113.output
> Add diagnostic when missing yield* in return Effect

- .changeset/rotten-worms-glow.md
- src/core/LSP.ts
- src/diagnostics/duplicatePackage.ts
- src/diagnostics/floatingEffect.ts
- src/diagnostics/genericEffectServices.ts
- src/diagnostics/leakingRequirements.ts
- src/diagnostics/missingEffectContext.ts
- src/diagnostics/missingEffectError.ts
- src/diagnostics/missingReturnYieldStar.ts
- src/diagnostics/missingStarInYieldEffectGen.ts
- src/diagnostics/returnEffectInGen.ts
- src/diagnostics/unnecessaryEffectGen.ts
- src/diagnostics/unnecessaryPipe.ts
- test/__snapshots__/diagnostics/leakingRequirements.ts.output
- test/__snapshots__/diagnostics/leakingRequirements_genericTag.ts.output
> Move default diagnostic severity to rule definition

- .changeset/honest-things-sip.md
- src/core/Nano.ts
> Micro perf opt

- .changeset/large-baboons-chew.md
- src/completions/middlewareAutoImports.ts
Fix barrelImportPackages duplicate imports
> Fix barrelImportPackages duplicate imports

- .changeset/pink-cameras-leave.md
- README.md
- src/completions/middlewareAutoImports.ts
- src/core/TypeScriptApi.ts
- src/diagnostics/importFromBarrel.ts
- tsconfig.base.json
Allow wildcard * at end of ImportPackages settings
> Allow wildcard * at end of ImportPackages settings

- .changeset/tangy-trains-live.md
- package.json
- pnpm-lock.yaml
- src/quickinfo/layerInfo.ts
Use pako for mermaid url generation
> Use pako for mermaid url generation

- .changeset/four-maps-ask.md
- README.md
- examples/completions/durationInput.ts
- examples/completions/durationInput_props.ts
- src/completions.ts
- src/completions/durationInput.ts
- src/core/LSP.ts
- test/__snapshots__/completions.test.ts.snap
> Add completions suggestions for DurationInput values

- src/cli.ts
> continue cli

- .changeset/chubby-lights-follow.md
- examples/diagnostics/leakingRequirements_noScope.ts
- src/core/Nano.ts
- src/core/TypeCheckerApi.ts
- src/diagnostics/leakingRequirements.ts
- src/diagnostics/tryCatchInEffectGen.ts
- src/quickinfo/layerInfo.ts
- test/__snapshots__/diagnostics/leakingRequirements_noScope.ts.codefixes
- test/__snapshots__/diagnostics/leakingRequirements_noScope.ts.output
- test/__snapshots__/diagnostics/tryCatchInEffectGen.ts.output
Scope is now marked as a service that can "leak".
> Allow scope to be a leaking service

- .changeset/empty-regions-enjoy.md
- README.md
- examples/diagnostics/unnecessaryPipeChain.ts
- src/diagnostics.ts
- src/diagnostics/tryCatchInEffectGen.ts
- src/diagnostics/unnecessaryPipeChain.ts
- test/__snapshots__/completions.test.ts.snap
- test/__snapshots__/diagnostics/unnecessaryPipeChain.ts.codefixes
- test/__snapshots__/diagnostics/unnecessaryPipeChain.ts.output
- test/__snapshots__/diagnostics/unnecessaryPipeChain.ts.unnecessaryPipeChain_fix.from106to185.output
- test/__snapshots__/diagnostics/unnecessaryPipeChain.ts.unnecessaryPipeChain_fix.from209to290.output
- test/__snapshots__/diagnostics/unnecessaryPipeChain.ts.unnecessaryPipeChain_skipFile.from106to185.output
- test/__snapshots__/diagnostics/unnecessaryPipeChain.ts.unnecessaryPipeChain_skipFile.from209to290.output
- test/__snapshots__/diagnostics/unnecessaryPipeChain.ts.unnecessaryPipeChain_skipNextLine.from106to185.output
- test/__snapshots__/diagnostics/unnecessaryPipeChain.ts.unnecessaryPipeChain_skipNextLine.from209to290.output
> Add warning for unnecessary pipe chains

- .changeset/cute-laws-cover.md
- src/core/LSP.ts
Skips entirely execution of disabled rules
> Skip entirely execution of disabled rules

- .changeset/violet-maps-slide.md
- README.md
- examples/completions/schemaBrand.ts
- src/completions.ts
- src/completions/schemaBrand.ts
- test/__snapshots__/completions.test.ts.snap
Add autocompletion for schema brand id
> Add autocompletion for Schema.brand

- README.md
Document additional steps required by emacs
> Add emacs setup steps

- .changeset/little-clouds-strive.md
- src/index.ts
Move codefixes registration hack into init phase
> Move codefixes registration hack into init phase

- .changeset/heavy-kids-smile.md
- src/index.ts
Ensure that diagnostics are collected before codefixes
> Ensure that diagnostics are collected before codefixes

- .changeset/pink-forks-jog.md
- src/completions/middlewareAutoImports.ts
- src/core/AutoImport.ts
- src/core/TypeScriptApi.ts
- test/autoimport.test.ts
Support effect-smol style categorization
> Refactor auto-imports to support multiple entrypoints

- .changeset/seven-results-visit.md
- README.md
- examples/refactors/writeTagClassAccessors.ts
- src/core/TypeParser.ts
- src/refactors.ts
- src/refactors/writeTagClassAccessors.ts
- test/__snapshots__/refactors/writeTagClassAccessors.ts.ln5col7.output
Automatically generates services accessors from definition
> add Implement Service accessors refactor

- .changeset/hip-cases-begin.md
- examples/diagnostics/classSelfMismatch_unionGiven.ts
- src/diagnostics/classSelfMismatch.ts
- test/__snapshots__/diagnostics/classSelfMismatch_unionGiven.ts.classSelfMismatch_fix.from229to253.output
- test/__snapshots__/diagnostics/classSelfMismatch_unionGiven.ts.classSelfMismatch_skipFile.from229to253.output
- test/__snapshots__/diagnostics/classSelfMismatch_unionGiven.ts.classSelfMismatch_skipNextLine.from229to253.output
- test/__snapshots__/diagnostics/classSelfMismatch_unionGiven.ts.codefixes
- test/__snapshots__/diagnostics/classSelfMismatch_unionGiven.ts.output
- test/__snapshots__/diagnostics/outdatedEffectCodegen.ts.outdatedEffectCodegen_fix.from61to87.output
Fix name of autofix suggestion
- Related Issue #
- Closes #390
> Fix name of autofix suggestion
